app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import settings


urlpatterns = [path('admin/', admin.site.urls), path('', include('shortener.urls'))]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

app/shortener/urls.py
from django.urls import path

from . import views

app_name = 'shortener'
urlpatterns = [path('', views.index, name='index'), path('<str:short_code>', views.parse, name='parse')]

app/shortener/models.py
from django.db import models
from django.utils import timezone
from django.utils.crypto import get_random_string


class UrlModel(models.Model):
    long_url = models.URLField(primary_key=True, verbose_name="Url original")
    short_code = models.CharField(
        unique=True, max_length=15, verbose_name="Código curto", help_text="Máximo de 15 caracteres"
    )
    expiry_date = models.DateTimeField(blank=True, null=True, verbose_name="Data de validade")
    created_at = models.DateTimeField(auto_now_add=True, editable=False, verbose_name="Data de criação")

    def __str__(self):
        return self.short_code

    def _has_expired(self) -> bool:
        if self.expiry_date is None:
            return False

        return self.expiry_date < timezone.now()

    has_expired = property(_has_expired)

    def save(self, *args, **kwargs) -> None:
        if not self.short_code:
            self.short_code = get_random_string(10)

        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Url'
        verbose_name_plural = 'Urls'
        db_table = 'urls'

app/shortener/views.py
import traceback
from typing import Optional
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from utils.misc import base_context

from .models import UrlModel


def index(request: HttpRequest) -> HttpResponse:
    try:
        status = 200
        context = {**base_context}
        if request.method == 'POST':
            long_url: str = request.POST.get('long_url')
            if not long_url:
                context['error_message'] = 'Please provide a URL to shorten.'
                status = 400
                return render(request, 'index.html', context, status=status)

            url_model_instance, _ = UrlModel.objects.get_or_create(long_url=long_url)
            if url_model_instance.has_expired:
                url_model_instance.delete()
                url_model_instance = UrlModel.objects.create(long_url=long_url)

            context['short_url'] = request.build_absolute_uri(f'/{url_model_instance.short_code}')
            status = 201

        return render(request, 'index.html', context, status=status)
    except:
        traceback.print_exc()

        return HttpResponse(status=500)


def parse(_request: HttpRequest, short_code: Optional[str]) -> HttpResponse:
    try:
        url_model_instance = UrlModel.objects.get(short_code=short_code)

        return HttpResponseRedirect(url_model_instance.long_url)
    except UrlModel.DoesNotExist:
        return HttpResponse(status=404)
    except:
        traceback.print_exc()

        return HttpResponse(status=500)

app/shortener/templates/base.html
<!DOCTYPE html>
<html lang="pt-BR" class="w-full h-full overflow-hidden bg-white">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
      rel="stylesheet"
    />
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    <style type="text/tailwindcss">
      :root {
        --primary: #f3f3f3;
        --secondary: cornflowerblue;
      }

      /* Firefox */
      * {
        scrollbar-width: thin;
        scrollbar-color: var(--secondary) var(--primary);
      }

      /* Chrome, Edge, and Safari */
      *::-webkit-scrollbar {
        width: 15px;
      }

      *::-webkit-scrollbar-track {
        background: var(--primary);
        border-radius: 5px;
      }

      *::-webkit-scrollbar-thumb {
        background-color: var(--secondary);
        border-radius: 14px;
        border: 3px solid var(--primary);
      }

      @layer base {
        html {
          font-family: Inter, system-ui, sans-serif;
        }
      }
    </style>
  </head>
  <body class="w-full h-full overflow-auto mx-auto">
    <div class="flex flex-col items-center justify-between px-8 py-12 min-h-screen">
      {% include "header.html" %}
      <main class="max-w-7xl mx-auto">{% block content %} {% endblock %}</main>
      {% include "footer.html" %}
    </div>
    <script type="text/javascript">
      async function copyToClipboard(text) {
        // Navigator clipboard api needs a secure context (https)
        if (navigator.clipboard && window.isSecureContext) await navigator.clipboard.writeText(text);
        else {
          // Use the 'out of viewport hidden text area' trick
          const textArea = document.createElement('textarea');
          textArea.value = text;

          // Move textarea out of the viewport so it's not visible
          textArea.style.position = 'absolute';
          textArea.style.left = '-999999px';

          document.body.prepend(textArea);
          textArea.select();

          try {
            document.execCommand('copy');
          } catch (error) {
            console.error(error);
          } finally {
            textArea.remove();
          }
        }
      }

      onClickCopy = _ => copyToClipboard(document.getElementById('short_url').value);
    </script>
  </body>
</html>

app/shortener/templates/footer.html
<footer class="clear-both w-full sm:z-auto mt-auto">
  <p class="text-gray-700 text-xs">
    &copy; {{ current_year }} {{ app_name }}. All Rights Reserved.
  </p>
</footer>

app/shortener/templates/index.html
{% extends "base.html" %} {% block content %}
<form action="{% url 'shortener:index' %}" method="post">
  {% csrf_token %}
  <fieldset class="space-y-4">
    <div class="space-y-2">
      <label for="long_url" class="block text-sm font-medium leading-6 text-gray-900">Long URL</label>
      <div class="relative rounded-md shadow-sm">
        <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
          <img
            class="h-5 w-5"
            src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAACXBIWXMAAAsTAAALEwEAmpwYAAACGElEQVR4nO2Zy0rDQBSGv67VuvMFVHTlbeOiCEpbd30i9TGEWjfi1voM3kAR3VlofQQr9VrErioDJ3Ao2iZNzExCPgi0IZk5f3POmflTyMjISAJl4BBoAV05zOcaUCIBzAOXQH/EcQ7M4SibwIsE+gTsAMvAhBwrwC7Qlms6wAaOUQS+JMATYGrItXngVImZc1FEFcj5uCcH1FWaJVKEfjJempWSKsJjV+433cwKWxGIQBpAX1pz7CwCrxGIQJqCGeeDmDFBX6nuFEaEVSFltU4Ma7FBU6tJzBzLxGaxi4I9Ge+AmHmUiZciGGtatV/TAWPlWyaeDDlOTq3uZ1jgXSY3eyfNDHANXPgUUVVblFks0JAATJFqEQ9y/jaAiC/ZaFrBBNED1n8R8SDf/YooYpECUEm6CI3TIsoD9vRdauJAnsQ4IvKqO/27iFH2tOcjnUzNrCo3uCaL3bPqTpu27emowq6I2L9+iLP/brFB7OmwdCpIDTQkHbuydzIpWXTJFAWpiVgpRiCiMtAAEiliXWrC3J8Ie3r3RzqtqvOxs6C6k197egPc/1ITkzLOGxa4SIM93U6LPT1Kiz1tpsWe9tJiTz8jEGJE7Nt+g94KmVrO2NOaBGFeGAfFKWdXGrP9OiXC41wCqgf4I8Y5EUhxdpQYY0GdsKfjsKHEtKVmrNrTsE/GS7O+TXsaZQOoyarfjdueZmRkEJofMI0LxuO9LrIAAAAASUVORK5CYII="
          />
        </div>
        <div class="flex items-center gap-x-4">
          <input
            type="url"
            name="long_url"
            id="long_url"
            class="block w-full rounded-md border-0 py-1.5 pl-10 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-blue-600 sm:text-sm sm:leading-6"
            placeholder="example.com"
          /><button
            class="rounded-md bg-blue-600 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-blue-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600"
            type="submit"
          >
            Shorten
          </button>
        </div>
      </div>
    </div>
    {% if short_url %}
    <div class="space-y-2">
      <label for="short_url" class="block text-sm font-medium leading-6 text-gray-900">Shorten URL</label>
      <div class="flex items-center gap-x-2">
        <input
          type="url"
          name="short_url"
          id="short_url"
          class="block w-full rounded-md border-0 py-1.5 pl-2 sm:pl-4 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-blue-600 sm:text-sm sm:leading-6 disabled:bg-gray-200"
          value="{{ short_url }}"
          disabled
        />
        <button type="button" onclick="onClickCopy()">
          <svg class="h-5 w-5 text-gray-900 hover:text-gray-800" viewBox="0 0 52 52" fill="currentColor">
            <g>
              <path
                d="M17.4,11.6h17.3c0.9,0,1.6-0.7,1.6-1.6V6.8c0-2.6-2.1-4.8-4.7-4.8h-11c-2.6,0-4.7,2.2-4.7,4.8V10
           C15.8,10.9,16.5,11.6,17.4,11.6z"
                clip-rule="evenodd"
                fill-rule="evenodd"
              />
              <path
                d="M43.3,6h-1.6c-0.5,0-0.8,0.3-0.8,0.8V10c0,3.5-2.8,6.4-6.3,6.4H17.4c-3.5,0-6.3-2.9-6.3-6.4V6.8
           c0-0.5-0.3-0.8-0.8-0.8H8.7C6.1,6,4,8.2,4,10.8v34.4C4,47.8,6.1,50,8.7,50h34.6c2.6,0,4.7-2.2,4.7-4.8V10.8C48,8.2,45.9,6,43.3,6z"
                clip-rule="evenodd"
                fill-rule="evenodd"
              />
            </g>
          </svg>
        </button>
      </div>
    </div>
    {% endif %} {% if error_message %}
    <p class="text-red-500 font-semibold text-sm">{{ error_message }}</p>
    {% endif %}
  </fieldset>
</form>
{% endblock %}